### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by poldi71** [DumpsterDave/FS22_BetterMissions#1]
Hello, i have a translation for your mod in german. If you want, you can do this in your mod.

**Comment by poldi71** [comment]
[translation_de.zip](https://github.com/DumpsterDave/FS22_BetterMissions/files/8041592/translation_de.zip)

**Comment by DumpsterDave** [comment]
Cool, Thankyou.  Any chance you can also translate the description in the moddesc.xml for me as well?  Google translate looks a little funky so I'm not sure I trust that it's correct.

**Comment by poldi71** [comment]
I think that's ok in German 
" Berechnet die Missionserträge neu, und erweitert die Missionsbeschreibungen. "

**Comment by DumpsterDave** [comment]
Should be all set now.  Thanks for the submission.  I've listed you as the contributor in the translation file.
